---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj-test-ryanj-t-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevLab/ryanj-test-frontend-gitops
